import type { Brief } from "../lib/brief";
import { createRepoFromTemplate, commitFiles, type GhCommitFile } from "../lib/github";
import type { PageBlueprint } from "./strategy";
import type { ImagesOutput } from "./images";
import type { Backlink } from "../lib/dataforseo";

export type RepoCreateOutput = {
  repoFullName: string;
  htmlUrl: string;
  defaultBranch: string;
  owner: string;
  name: string;
};

export type RepoCommitOutput = {
  repoFullName: string;
  htmlUrl: string;
  defaultBranch: string;
  commitSha: string;
};

// Template lives on fluxgateseo (forked from andreabbo) so we can keep the
// is_template flag on without depending on andreabbo's repo settings.
const DEFAULT_TEMPLATE_OWNER = "fluxgateseo";
const DEFAULT_TEMPLATE_REPO = "elite-astro-template";

export type RepoCreateInput = {
  brief: Brief;
  env: { GITHUB_TOKEN?: string };
  templateOwner?: string;
  templateRepo?: string;
  newOwner?: string;
  fetcher?: typeof fetch;
};

export async function runRepoCreate(input: RepoCreateInput): Promise<RepoCreateOutput> {
  if (!input.env.GITHUB_TOKEN) throw new Error("GITHUB_TOKEN not set");
  const domain = input.brief.step1.domain;
  const slugBase = domain.replace(/^www\./, "").split(".")[0];
  const repoName = `site-${slugBase}`;

  // POST /repos/{template_owner}/{template_repo}/generate creates a new repo
  // pre-populated with all template files in a single API call. Requires the
  // source repo to have "Template repository" enabled in Settings.
  const repo = await createRepoFromTemplate({
    token: input.env.GITHUB_TOKEN,
    templateOwner: input.templateOwner ?? DEFAULT_TEMPLATE_OWNER,
    templateRepo: input.templateRepo ?? DEFAULT_TEMPLATE_REPO,
    newOwner: input.newOwner ?? "",
    newName: repoName,
    privateRepo: true,
    description: `${input.brief.step4?.businessName ?? domain} — generated by elite-pipeline-workflow`,
    fetcher: input.fetcher,
  });
  const owner = repo.fullName.split("/")[0];
  return {
    repoFullName: repo.fullName,
    htmlUrl: repo.htmlUrl,
    defaultBranch: repo.defaultBranch,
    owner,
    name: repoName,
  };
}

export type RepoCommitInput = {
  brief: Brief;
  account: "IT" | "EN";
  pages: PageBlueprint[];
  contentBySlug: Map<string, string>;
  images: ImagesOutput;
  backlinks: Backlink[];
  repo: RepoCreateOutput;
  env: { GITHUB_TOKEN?: string };
  fetcher?: typeof fetch;
};

/**
 * Commit-overlay step. Stage 5a created the repo from template, so the
 * template's files are already there. Here we add only what's new: per-page
 * markdown, site config, image manifest, README replacement.
 *
 * Subrequest count: 1 (get ref) + 1 (get base commit) + N (one blob per
 * file in `out`, ~17) + 1 (tree) + 1 (commit) + 1 (ref update) ≈ 21.
 * Stays well under the 50-per-invocation limit.
 */
export async function runRepoCommitOverlay(input: RepoCommitInput): Promise<RepoCommitOutput> {
  if (!input.env.GITHUB_TOKEN) throw new Error("GITHUB_TOKEN not set");
  const domain = input.brief.step1.domain;

  const out: GhCommitFile[] = [];

  // Generated content per page. Blog articles go to src/content/articoli/
  // (where the template's `articoli` collection loader reads) and have their
  // frontmatter transformed to that collection's schema; everything else is a
  // plain page. Writing blog posts to src/content/blog/ (the old path) left
  // them outside any collection, so /blog stayed empty.
  for (const p of input.pages) {
    const md = input.contentBySlug.get(p.slug);
    if (!md) continue;
    if (p.type === "blog-article") {
      out.push({ path: `src/content/articoli/${p.slug}.md`, content: toArticoloMarkdown(md, p, input.images), encoding: "utf-8" });
    } else {
      out.push({ path: `src/content/pages/${p.slug}.md`, content: md, encoding: "utf-8" });
    }
  }

  // site.config.ts — uses defineSiteConfig from the template's
  // src/lib/site-config.ts. Do NOT overwrite that file (it's the type+
  // function definitions); we only write our DATA to src/site.config.ts.
  out.push({
    path: "src/site.config.ts",
    content: renderSiteConfig({ brief: input.brief, account: input.account, repoFullName: input.repo.repoFullName }),
    encoding: "utf-8",
  });

  // astro site URL helper
  out.push({
    path: "astro.config.site.mjs",
    content: `export const siteUrl = "https://${domain}";\n`,
    encoding: "utf-8",
  });

  // image manifest
  out.push({
    path: "src/data/images.json",
    content: JSON.stringify(input.images.pages, null, 2),
    encoding: "utf-8",
  });

  // gallery data — the template's /galleria page reads src/data/gallery.json
  // and ships an empty [] placeholder, so without this every generated site
  // had an empty gallery. Populate it from the Stage-4 images.
  out.push({
    path: "src/data/gallery.json",
    content: buildGalleryJson(input.images, input.pages),
    encoding: "utf-8",
  });

  // backlinks recovery data — raw historical backlinks + a slug map of pages
  // marked as link-equity destinations. Site middleware (functions/_middleware.ts
  // in the template) can use this to 301-redirect old paths or to render
  // analytics-aware UTM/referrer logic.
  const linkEquityDestinations = input.pages
    .filter((p) => p.linkEquityDestination)
    .map((p) => p.slug);
  out.push({
    path: "src/data/backlinks.json",
    content: JSON.stringify({
      backlinks: input.backlinks.map((b) => ({
        domainFrom: b.domainFrom,
        url: b.url,
        anchor: b.anchor,
        domainRank: b.domainRank,
      })),
      linkEquityDestinations,
      generatedAt: new Date().toISOString(),
    }, null, 2),
    encoding: "utf-8",
  });

  // README replacement
  out.push({
    path: "README.md",
    content: `# ${input.brief.step4?.businessName ?? domain}\n\nGenerated by elite-pipeline-workflow on ${new Date().toISOString()}.\n\nDomain: \`${domain}\` (account: ${input.account})\n`,
    encoding: "utf-8",
  });

  const commit = await commitFiles({
    token: input.env.GITHUB_TOKEN,
    owner: input.repo.owner,
    repo: input.repo.name,
    branch: input.repo.defaultBranch,
    message: `feat: scaffold site for ${domain}`,
    files: out,
    fetcher: input.fetcher,
  });

  return {
    repoFullName: input.repo.repoFullName,
    htmlUrl: input.repo.htmlUrl,
    defaultBranch: input.repo.defaultBranch,
    commitSha: commit.commitSha,
  };
}

export function renderSiteConfig(args: { brief: Brief; account: "IT" | "EN"; repoFullName: string }): string {
  const b = args.brief;
  const business = b.step4;
  const colors = b.step7?.customColors ?? { primary: "#000000", accent: "#3b82f6", background: "#ffffff" };
  // Map design style values to template's lowercase enum.
  const styleMap: Record<string, string> = { Editorial: "editorial", Modern: "modern", Elegant: "elegant", Bold: "bold" };
  const style = styleMap[b.step7?.designStyle ?? "Editorial"] ?? "editorial";
  const industryMap: Record<string, string> = {
    Ristorazione: "ristorazione", "Beauty/Wellness": "beauty", "Tech/SaaS": "tech",
    "Servizi professionali": "servizi", "E-commerce": "ecommerce", Turismo: "turismo",
    Salute: "salute", Educazione: "educazione", Altro: "altro",
  };
  const industry = industryMap[business?.industry ?? "Altro"] ?? "altro";

  const config = {
    name: business?.businessName ?? "",
    tagline: business?.usp ?? "",
    description: business?.description ?? "",
    domain: b.step1.domain,
    industry,
    subCategory: business?.subCategory ?? "",
    language: "it",
    address: {
      street: business?.address ?? "",
      city: business?.city ?? "",
      country: "IT",
    },
    phone: business?.phone ?? "",
    email: business?.email ?? "",
    design: {
      style,
      palette: { primary: colors.primary, accent: colors.accent, background: colors.background },
      fontPairing: { display: "Playfair Display", body: "Inter" },
      darkMode: "auto",
    },
    voice: {
      tone: Math.min(5, Math.max(1, b.step8?.toneFormal ?? 3)),
      traits: b.step8?.voiceTraits ?? [],
      avoidWords: (b.step8?.avoidWords ?? "").split(/[,;]\s*/).filter(Boolean),
      brandKeywords: (b.step8?.brandKeywords ?? "").split(/[,;]\s*/).filter(Boolean),
    },
    pages: {
      home: b.step9?.pages?.home ?? true,
      chiSiamo: b.step9?.pages?.chiSiamo ?? true,
      galleria: b.step9?.pages?.galleria ?? false,
      eventi: b.step9?.pages?.eventi ?? false,
      blog: b.step9?.pages?.blog ?? true,
      faq: b.step9?.pages?.faq ?? true,
      contatti: b.step9?.pages?.contatti ?? true,
    },
    leadCapture: {
      form: (b.step9?.leadCapture ?? "form") !== "phone",
      phone: (b.step9?.leadCapture ?? "form") !== "form",
      whatsappButton: false,
    },
    gdpr: { cookieBanner: b.step10?.gdprBanner ?? false },
    seo: {},
    layout: {
      hero: b.step7?.layout?.hero ?? "hero-fullbleed",
      sections: b.step7?.layout?.sections ?? [
        "section-featured-dishes",
        "section-story",
        "section-photo-mosaic",
        "section-blog-feed",
        "section-cta-banner",
      ],
      categoryLayout: b.step7?.layout?.categoryLayout ?? "cat-grid-cards",
      heroAssets: {},
    },
  };

  return `// Auto-generated by elite-pipeline-workflow. Do not edit by hand.
// Account: ${args.account} · Source repo: ${args.repoFullName}
import { defineSiteConfig } from "./lib/site-config";

export default defineSiteConfig(${JSON.stringify(config, null, 2)});
`;
}

// ── Gallery + blog-article helpers ────────────────────────────────────────

function yamlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

type ParsedMarkdown = { data: Record<string, string>; body: string };

/** Parse a content-stage markdown's flat (single-level) YAML frontmatter. */
export function parseFrontmatter(md: string): ParsedMarkdown {
  const m = md.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: md.trim() };
  const data: Record<string, string> = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (kv) data[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
  }
  return { data, body: m[2].trim() };
}

/**
 * Transform a content-stage markdown (frontmatter: title/description/slug/image)
 * into the template's `articoli` collection schema (title/date/category/excerpt
 * + optional hero{src,alt}). Without this, blog posts fail the collection's Zod
 * schema (date/category/excerpt are required) and break the build.
 */
export function toArticoloMarkdown(md: string, page: PageBlueprint, images: ImagesOutput): string {
  const { data, body } = parseFrontmatter(md);
  const title = data.title || page.title || page.h1;
  const excerpt = data.description || data.excerpt || page.brief.slice(0, 160);
  const date = new Date().toISOString().slice(0, 10);
  const category = data.category || "Blog";
  const heroEntry = images.pages.find((p) => p.slug === page.slug);
  const heroUrl = heroEntry?.hero?.url;

  const lines = [
    "---",
    `title: ${yamlString(title)}`,
    `date: ${yamlString(date)}`,
    `category: ${yamlString(category)}`,
    `excerpt: ${yamlString(excerpt)}`,
    `slug: ${yamlString(data.slug || page.slug)}`,
  ];
  if (heroUrl) {
    lines.push("hero:", `  src: ${yamlString(heroUrl)}`, `  alt: ${yamlString(title)}`);
  }
  lines.push("---", "", body, "");
  return lines.join("\n");
}

/**
 * Build src/data/gallery.json from the Stage-4 images: each page's hero + body
 * images, deduped by URL, captioned with the page's H1/title. Caps the set so a
 * many-page site doesn't produce an unwieldy gallery.
 */
export function buildGalleryJson(images: ImagesOutput, pages: PageBlueprint[]): string {
  const labelBySlug = new Map(pages.map((p) => [p.slug, p.h1 || p.title]));
  const seen = new Set<string>();
  const items: { src: string; alt: string; caption: string }[] = [];
  for (const pg of images.pages) {
    const label = labelBySlug.get(pg.slug) ?? pg.slug;
    for (const hit of [pg.hero, ...pg.body]) {
      if (!hit || !hit.url || seen.has(hit.url)) continue;
      seen.add(hit.url);
      items.push({ src: hit.url, alt: label, caption: label });
    }
  }
  return JSON.stringify(items.slice(0, 24), null, 2) + "\n";
}
